name: 'Close stale issues and PRs'
on:
  schedule:
    - cron: '30 1 * * *' # Runs every day at 01:30 UTC

jobs:
  stale:
    uses: NitroNvim/.github/.github/workflows/stale.yml@main
    secrets: inherit
